#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv
  ln -nfs ../vendor/virtualenv/bin/bumpversion "$shome/bin/"
}

bootstrap
